---
services:
  # bind mount example
  linuxgsm-scpslsm-bind:
    image: gameservermanagers/gameserver:scpslsm
    # image: ghcr.io/gameservermanagers/gameserver:scpslsm
    container_name: scpslsmserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/scpslsmserver:/data
    network_mode: host

  # volume example
  linuxgsm-scpslsm-volume:
    image: gameservermanagers/gameserver:scpslsm
    # image: ghcr.io/gameservermanagers/gameserver:scpslsm
    container_name: scpslsmserver
    restart: unless-stopped
    volumes:
      - linuxgsm-scpslsm:/data
    network_mode: host

volumes:
  linuxgsm-scpslsm:
