version: "3.8"
services:
  # bind mount example
  linuxgsm-ahl-bind:
    image: gameservermanagers/gameserver:ahl
    # image: ghcr.io/gameservermanagers/gameserver:ahl
    container_name: ahlserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-ahl-volume:
    image: gameservermanagers/gameserver:ahl
    # image: ghcr.io/gameservermanagers/gameserver:ahl
    container_name: ahlserver
    restart: unless-stopped
    volumes:
      - linuxgsm-ahl:/data
    ports:

volumes:
  linuxgsm-ahl:
